name: "📰 Suggestion de news pour une revue de presse"
description: "Formulaire pour proposer une news à une revue de presse."
labels: [
  "contribution externe",
  "rdp",
  "triage"
  ]
assignees:
  - Guts

body:
  - type: markdown
    attributes:
      value: |
        Merci de prendre le temps de contribuer à Geotribu !

  - type: checkboxes
    id: cb-author-content-relationship
    attributes:
      label: "Avez-vous un lien avec le contenu proposé ?"
      description: Mise en avant du travail d'un tiers ? Auto-promo ? Publicité ?
      options:
        - label: Oui
        - label: Non

  - type: dropdown
    id: section
    attributes:
      label: Section / catégorie
      description: "A quelle [section ou catégorie](https://static.geotribu.fr/contribuer/rdp/add_news/#sections-categories) rattacher la news ?"
      options:
        - Sorties de la semaine
        - Logiciel
        - Représentation Cartographique
        - OpenStreetMap
        - Google
        - Open Data
        - Geo-event
        - Divers
        - En bref
    validations:
      required: true

  - type: input
    id: in-author-mail
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true


  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
