rss:
  abstract_chars_count: 500
  categories:
    - categories
    - tags
  comments_path: "#__comments"
  date_from_meta:
    as_creation: "date"
    datetime_format: "%Y-%m-%d %H:%M"
    default_timezone: Europe/Paris
    default_time: "14:00"
  enabled: !ENV [MKDOCS_ENABLE_PLUGIN_RSS, false]
  image: "https://cdn.geotribu.fr/img/internal/charte/geotribu_logo_64x64.png"
  length: 50
  match_path: "(articles|rdp)/.*"
  pretty_print: false
  url_parameters:
    utm_source: "rss-feed"
    utm_medium: "RSS"
    utm_campaign: "feed-syndication"
