git-committers:
  enabled: !ENV [MKDOCS_ENABLE_PLUGIN_GIT_COMMITTERS, false]
  branch: master
  cache_dir:
    !ENV [
      MKDOCS_PLUGIN_GIT_COMMITTERS_CACHE_DIR,
      .cache/plugins/git-committers/,
    ]
  docs_path: content/
  repository: geotribu/website
  token: !ENV ["GH_TOKEN_MATERIAL_INSIDERS", !ENV ["GITHUB_TOKEN"]]
