name: "✅ Markdown header check"

on:
  pull_request:
    types: [labeled]
    paths:
      - "content/articles/**/*.md"

jobs:
  header-check:
    name: "👓 Vérification du header markdown de l'article"
    runs-on: ubuntu-latest
    if: ${{ github.event.label.name == 'articles' }}

    steps:
      - name: "Récupère le code source"
        uses: actions/checkout@v4

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          cache: "pip"
          python-version: 3.11

      - name: "Installer dépendances"
        run: |
          python -m pip install -U pip setuptools wheel
          python -m pip install -U -r requirements.txt

      - name: "Vérifie les entêtes markdown avec le CLI"
        run: |
          geotribu header-check content/articles/2024/*.md --authors-folder content/team -minw 250 -maxw 1000 -v
