name: "🎳 Markdown Linter"

# Trigger
on:
  pull_request:
    branches: [master]
    paths:
      - "content/**/*.md"

jobs:
  lint-markdown-review:
    name: "👓 Vérification de la syntaxe"
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'geotribu' }}

    steps:
      - name: "Récupère le code source"
        uses: actions/checkout@v3

      # Filter results by added/modified lines.
      - name: "Vérifie la syntaxe des lignes ajoutées ou modifiées"
        id: markdownlint-github-pr-review-added
        uses: reviewdog/action-markdownlint@v0.7.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_error: true
          filter_mode: added
          reporter: github-pr-review

      - name: "Explications sur les erreurs du linter"
        id: pr-comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: ${{ failure() && steps.markdownlint-github-pr-review-added.conclusion == 'failure' }}
        with:
          header: linter-md-error
          recreate: true
          message: |
            Des erreurs de syntaxe Markdown ont été détectées dans les lignes ajoutées ou modifiées. Merci de les corriger ou de les marquer comme faux-positif :

              - [règles de syntaxe Markdown applicables à Geotribu](https://static.geotribu.fr/contribuer/guides/markdown_quality/)
              - [marquer une erreur de syntaxe comme faux-positif](https://static.geotribu.fr/contribuer/guides/markdown_quality/)

      # Filter results by added/modified file. i.e. reviewdog will report results
      # as long as they are in added/modified file even if the results are not in actual diff.
      - name: "Vérifie la syntaxe de tous les fichiers ajoutés ou modifiés"
        id: markdownlint-github-pr-review-file
        uses: reviewdog/action-markdownlint@v0.7.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_error: false
          filter_mode: file
          level: warning
          reporter: github-pr-review

      - name: "Félicitations"
        id: pr-comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: ${{ success() }}
        with:
          header: linter-md-success
          recreate: true
          message: |
            :clap: Le markdown ajouté est impeccable ! Merci :1st_place_medal:
