name: "🎳 Markdown Linter"

# Trigger
on:
  pull_request:
    branches: [master]
    paths:
      - "content/**/*.md"

jobs:
  lint-markdown-review:
    name: "👓 Vérification de la syntaxe"
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'geotribu' }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      # Filter results by added/modified lines.
      - name: markdownlint-github-pr-review-added
        uses: reviewdog/action-markdownlint@v0.7.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_error: true
          filter_mode: added
          reporter: github-pr-review

      # Filter results by added/modified file. i.e. reviewdog will report results
      # as long as they are in added/modified file even if the results are not in actual diff.
      - name: markdownlint-github-pr-review-file
        uses: reviewdog/action-markdownlint@v0.7.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_error: false
          filter_mode: file
          level: warning
          reporter: github-pr-review
